import type { Metadata } from "next";
import { DM_Sans, Nunito_Sans, Plus_Jakarta_Sans, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/global/header";
import Footer from "@/components/global/footer";

const dmSans = Poppins({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400"]
});

const nunitoSans = Plus_Jakarta_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${nunitoSans.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
